var btn_search = document.getElementById('icon-search');
var search_bar = document.getElementById('btn-search');
var btn_close = document.getElementById('icon-close');

btn_search.addEventListener('click', function () {
    search_bar.setAttribute("style", "display:flex");
    btn_search.setAttribute("style", "display:none");
    btn_close.setAttribute("style", "display:block")
});

btn_close.addEventListener('click', function () {
    search_bar.setAttribute("style", "display:none");
    btn_search.setAttribute("style", "display:block");
    btn_close.setAttribute("style", "display:none");
    resultado.setAttribute("style", "display:none");
    buscar.value = '';
})


//Para filtrar cada producto
const buscar = document.querySelector('#btn-search');
const resultado = document.querySelector('#resultado');
const productos = [
    { nombre: "Brida reforzada 3/4 - 1-1/16", url: "/pages/detalle_productos/Abrazadera%20sin%20fin%20reforzada%2010%20-%20Fiero.html" },
    { nombre: "Brida reforzada 3-5/16, 4-1/4", url: "/pages/detalle_productos/Abrazadera%20sin%20fin%20reforzada%2060%20-%20Fiero.html" },
    { nombre: "Aceite semi-sintetico de 4 tiempos", url: "/pages/detalle_productos/Aceite%20semi-sintetico%20de%204%20tiempos%20-%20truper.html" },
    { nombre: "Arnes de cuerpo completo con 3 anillos", url: "/pages/detalle_productos/Arnes%20de%20cuerpo%20completo%20-%20Truper.html" },
    { nombre: "Asiento redondo ligero con tapa para inodoro", url: "/pages/detalle_productos/Asiento%20redondo%20con%20tapa%20para%20WC%20-%20Foset.html" },
    { nombre: "Aspersor metalico de dos vias", url: "/pages/detalle_productos/Aspersor%20metalico%20de%20dos%20vias%20-%20Truper.html" },
    { nombre: "Aspersor metalico de una via", url: "/pages/detalle_productos/Aspersor%20metalico%20de%20una%20via%20-%20Truper.html" },
    { nombre: "Aspersor oscilatorio", url: "/pages/detalle_productos/Aspersor%20oscilatorio%20-%20Truper.html" },
    { nombre: "Azadon Lane de 1.6 lb", url: "/pages/detalle_productos/Azadon%20Lane%20de%201.6lb%20-%20Truper.html"},
    { nombre: "Azadon Lane de 2.1 lb", url: "/pages/detalle_productos/Azadon%20Lane%20de%202.1lb%20-%20Truper.html"},
    { nombre: "Bandola de acero de 5/16 con seguro", url: "/pages/detalle_productos/Bandola%20de%20acero%20de%205s16%20con%20seguro%20-%20Fiero.html"},
    { nombre: "Barra cavadora 1 x 130 cm, escoplo 102 mm", url: "/pages/detalle_productos/Barra%20cavadora%20de%20102mm%20-%20Truper.html"},
    { nombre: "Barra de punta de 1x175 cm, escoplo 72 mm", url: "/pages/detalle_productos/Barra%20de%20punta%20con%20escoplo%20de%2072%20mm%20-%20Truper.html"},
    { nombre: "Bascula capacidad 50 kg romana de resorte", url: "/pages/detalle_productos/Báscula%20capacidad%2050%20kg%20romana%20de%20resorte%20-%20Pretul.htmls"},
    { nombre: "Bascula digital para cocina", url: "/pages/detalle_productos/Bascula%20digital%20para%20cocina%20-%20Truper.html"},
    { nombre: "Bisagra rectangular 4' acero latonado", url: "/pages/detalle_productos/Bisagra%20rectangular%204'%20-%20Hermex.html"},
    { nombre: "Bisagra rectangular 3' acero latonado", url: "/pages/detalle_productos/Bisagra%20rectangular%20de%20acero%20latonado%20de%203'%20-%20Hermex.html"},
    { nombre: "Blíster con 4 pilas recargables", url: "/pages/detalle_productos/Blister%20de%20pilas%20AA%20-%20Volteck.html"},
    { nombre: "Bolsa con 1 kg de arandelas planas de 1/4'", url: "/pages/detalle_productos/Bolsa%20de%201%20kg%20de%20arandelas%20-%20Fiero.html"},
    { nombre: "Bomba centrífuga para agua modelo europeo, 1 HP", url: "/pages/detalle_productos/Bomba%20centrifuga%20para%20agua%20de%201%20HP%20-%20Truper.html"},
    { nombre: "Bomba manual para inflar, 100 PSI", url: "/pages/detalle_productos/Bomba%20manual%20para%20inflar%20de%20100%20PSI%20-%20Truper.html"},
    { nombre: "Bomba periférica 1/2 HP, altura máxima 20 m", url: "/pages/detalle_productos/Bomba%20periferica%201s2%20-%20Pretul.html"},
    { nombre: "Bomba periférica 3/4 HP, altura máxima 55 m", url: "/pages/detalle_productos/Bomba%20periferica%203s4%20-%20Truper.html"},
    { nombre: "Bomba periférica 1 HP, altura máxima 70 m", url: "/pages/detalle_productos/Bomba%20periferica%20de%201%20HP%20-%20Truper.html"},
    { nombre: "Bomba periférica 1 HP, altura máxima 60 m ", url: "/pages/detalle_productos/Bomba%20periferica%20de%201%20HP%20gris%20-%20Truper.html"},
    { nombre: "Bomba presurizadora multietapas 1/2 HP con control", url: "/pages/detalle_productos/Bomba%20presurizada%201s2%20-%20Truper.html"},
    { nombre: "Bomba sumergible acero inoxidable,agua sucia,1-1/2HP", url: "/pages/detalle_productos/Bomba%20sumergible%20de%20aceron%20inoxidable%201-1s2%20HP%20-%20Truper.html"},
    { nombre: "Bomba sumergible plástica, 1/2 HP para agua limpia", url: "/pages/detalle_productos/Bomba%20sumergible%20plastica%201s2%20-%20Truper.html"},
    { nombre: "Bomba sumergible, tipo bala, 1-1/2 HP, agua limpia", url: "/pages/detalle_productos/Bomba%20sumergible%20tipo%20bala%20%20de%201-1s2%20HP%20-%20Truper.html"},
    { nombre: "Bomba sumergible, tipo bala, 1 HP, agua limpia", url: "/pages/detalle_productos/Bomba%20sumergible%20tipo%20bala%20de%201%20HP%20-%20Truper.html"},
    { nombre: "Bomba hidroneumática 25L", url: "/pages/detalle_productos/bomba_hidroneumatica24L_truper.html"},
    { nombre: "Bota de seguridad negra, #25, casquillo de poliamida", url: "/pages/detalle_productos/Bota%20de%20seguridad%20negra,%2025%20-%20Pretul.html"},
    { nombre: "Botas industriales # 27 ", url: "/pages/detalle_productos/Botas%20industriales%2027%20-%20Truper.html"},
    { nombre: "Botas jardineras # 29", url: "/pages/detalle_productos/Botas%20jardineras%2029%20-%20Truper.html"},
    { nombre: "Broca escalonada óxido negro 11 escalones", url: "/pages/detalle_productos/Broca%20escalonada%20óxido%20negro%2011%20-%20Truper.html"},
    { nombre: "Broca HSS 7/16' Trublack para metal", url: "/pages/detalle_productos/Broca%20HSS%207s16%20Trublack%20para%20metal%20-%20Truper.html"},
    { nombre: "Broca para concreto de 3/8 x 6'", url: "/pages/detalle_productos/Broca%20para%20concreto%20de%203s8%20x%206'%20-%20Truper.html"},
    { nombre: "Broca para router, española, 1-1/4'", url: "/pages/detalle_productos/Broca%20para%20router,%20española%20-%20Truper.html"},
    { nombre: "Broca piloto de 1/4' para brocasierras diamante", url: "/pages/detalle_productos/Broca%20piloto%20de%20un%20cuarto%20para%20brocasierras%20diamante%20-%20Truper.html"},
    { nombre: "Broca HSS 1/4' Trublack para metal", url: "/pages/detalle_productos/Broca%20un%20cuarto%20Trublack%20para%20metal%20-%20Truper.html"},
    { nombre: "Cables pasa corriente 3 m, 225 A, 8 AWG, con funda", url: "/pages/detalle_productos/Cables%20pasa%20corriente%20-%20Truper.html"},
    { nombre: "Caja cosmetiquera 14¨, rosa/morado", url: "/pages/detalle_productos/Caja%20cosmetiquera%20-%20Pretul.html"},
    { nombre: "Caja para herramienta de 22¨", url: "/pages/detalle_productos/Caja%20de%20herramientas%20-%20Truper.html"},
    { nombre: "Calentador instantáneo modulante, 24L, 4 serv, gas LP", url: "/pages/detalle_productos/Calentador%20instantaneo%20modulante%20-%20Foset.html"},
    { nombre: "Candado de hierro 38 mm gancho corto en caja", url: "/pages/detalle_productos/Candado%20de%20hierro%20de%2038%20mm%20-%20Hermex.html"},
    { nombre: "Candado de hierro 50 mm gancho corto en caja", url: "/pages/detalle_productos/Candado%20de%20hierro%20de%2050%20mm%20-%20Hermex.html"},
    { nombre: "Candado italiano de gancho largo, 113", url: "/pages/detalle_productos/Candado%20italiano%20serie%20113%20-%20Yale.html"},
    { nombre: "Candado laminado, 30mm, gancho corto", url: "/pages/detalle_productos/Candado%20laminado%20de%2030%20mm%20-%20Hermex.html"},
    { nombre: "Candado serie 220", url: "/pages/detalle_productos/Candado%20serie%20220%20-%20Yale.html"},
    { nombre: "Carda copa 3¨ alambre ondulado fino, eje 5/8¨-11", url: "/pages/detalle_productos/Carda%20copa%20de%203'%20-%20Truper.html"},
    { nombre: "Careta electrónica p/soldar, semiprofesional, 9 a 13", url: "/pages/detalle_productos/Careta%20para%20soldar%20-%20Pretul.html"},
    { nombre: "Cargador c/arrancador de 50 A para baterías de 12 V", url: "/pages/detalle_productos/Cargador%20de%2050%20A%20para%20baterias%20-%20Truper.html"},
    { nombre: "Carretilla 4.5 ft3 Neumática, bastidor tubular", url: "/pages/detalle_productos/Carretilla%204.5%20ft%20-%20Truper.html"},
    { nombre: "Carretilla 5.5 ft3 Neumática, bastidor tubular", url: "/pages/detalle_productos/Carretilla%205.5%20ft%20-%20Truper.html"},
    { nombre: "Carro de servicio, 3 charolas", url: "/pages/detalle_productos/Carro%20de%20servicio%20con%203%20compartimentos%20-%20Truper.html"},
    { nombre: "Casco de seguridad, ajuste de matraca, amarillo", url: "/pages/detalle_productos/Casco%20de%20seguridad%20-%20Truper.html"},
    { nombre: "Cautín 48 W profesional para electrónica con estación", url: "/pages/detalle_productos/Cautin%2048%20W%20con%20estacion%20-%20Truper.html"},
    { nombre: "Cavador mangos de madera 48¨", url: "/pages/detalle_productos/Cavador%20con%20mangos%20de%20madera%20-%20Truper.html"},
    { nombre: "Centro de carga de sobreponer, 2 polos", url: "/pages/detalle_productos/Centro%20de%20carga%20de%202%20polos%20-%20Volteck.html"},
    { nombre: "Cepillo de alambre 64 pinceles de acero al carbono", url: "/pages/detalle_productos/Cepillo%20de%20alambre%20de%2064%20pinceles%20de%20acero%20-%20Truper.html"},
    { nombre: "Cepillo eléctrico 3-1/4¨, 850W ", url: "/pages/detalle_productos/Cepillo%20electrico%203-1s4'%20-%20Truper.html"},
    { nombre: "Cepillo tipo plancha de plástico", url: "/pages/detalle_productos/Cepillo%20tipo%20plancha%20de%20plastico%20-%20Klintek.html"},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
    { nombre: "", url: ""},
]

const filtrar = () => {
    resultado.setAttribute("style", "display:block")

    resultado.innerHTML = '';

    const texto = buscar.value.toLowerCase();

    for (let i of productos) {
        let producto = i.nombre.toLowerCase();
        if (producto.indexOf(texto) !== -1) {
            resultado.innerHTML += `
                <li>${i.nombre} <a href=${i.url} target="_blank">Ver Producto</a></li>
            `
        }
        
    }

    if (resultado.innerHTML === '') {
        resultado.innerHTML += `
                <li>Producto no encontrado</li>
            `
    }

    if(buscar.value == ''){
        resultado.setAttribute("style", "display:none")
    }
}

search_bar.addEventListener('keyup', filtrar);

